In [7]:
print(123)

123

In [8]:
a = 123

In [9]:
print(a)

123

In [10]:
b = 321

In [11]:
b

321

In [12]:
a
b

321

In [13]:
import pandas as pd

In [14]:
columns = ["Name", "Age", "Hight"]
data = [
    ["Ted", 22, 175],
    ["Allen", 25, 180],
]
df = pd.DataFrame(data=data, columns=columns)
df

    Name  Age  Hight
0    Ted   22    175
1  Allen   25    180

In [15]:
df["Weight"] = [75, 80]
df

    Name  Age  Hight  Weight
0    Ted   22    175      75
1  Allen   25    180      80

In [16]:
df.drop("Weight", axis=1)

    Name  Age  Hight
0    Ted   22    175
1  Allen   25    180

In [17]:
df

    Name  Age  Hight  Weight
0    Ted   22    175      75
1  Allen   25    180      80

In [18]:
df = df.drop("Weight", axis=1)
df

    Name  Age  Hight
0    Ted   22    175
1  Allen   25    180

In [19]:
df["Age"]

0    22
1    25
Name: Age, dtype: int64

In [20]:
df["age"]

KeyError: 'age'

In [ ]:
"""
select Age from df;
"""
df["Age"]

0    22
1    25
Name: Age, dtype: int64

In [22]:
"""
select Age + 1 from df;
"""
df["Age"] + 1

0    23
1    26
Name: Age, dtype: int64