In [1]:
import pandas as pd

df = pd.read_csv("./ptt.csv")
df

,推,噓,分數,作者,標題,時間
0,推: 25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020
1,推: 11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020
2,推: 20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020
3,推: 31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020
4,推: 106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020
...,...,...,...,...,...,...
833,推: 10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020
834,推: 7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020
835,推: 0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020
836,推: 15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020
837,推: 5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020

In [2]:
"""
Create a function to convert "推: 25" -> 25
"""
def col_transform(input_str: str) -> int:
    digit_str = input_str.split(":")[1].strip()
    return int(digit_str)

print(col_transform("推: 25"))

25

In [3]:
df["推"]

0       推: 25
1       推: 11
2       推: 20
3       推: 31
4      推: 106
        ...
833     推: 10
834      推: 7
835      推: 0
836     推: 15
837      推: 5
Name: 推, Length: 838, dtype: str

In [4]:
df["推"].apply(col_transform)

0       25
1       11
2       20
3       31
4      106
      ...
833     10
834      7
835      0
836     15
837      5
Name: 推, Length: 838, dtype: int64

In [5]:
df

,推,噓,分數,作者,標題,時間
0,推: 25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020
1,推: 11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020
2,推: 20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020
3,推: 31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020
4,推: 106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020
...,...,...,...,...,...,...
833,推: 10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020
834,推: 7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020
835,推: 0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020
836,推: 15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020
837,推: 5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020

In [6]:
df["推"] = df["推"].apply(col_transform)
df

,推,噓,分數,作者,標題,時間
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020
...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020

In [7]:
df["score_t"] = df["分數"].apply(col_transform)
df

,推,噓,分數,作者,標題,時間,score_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,21
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,0
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,20
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,29
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,100
...,...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,9
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,7
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,11
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,5

In [8]:
df["噓"].apply(lambda x: int(x.split(":")[1].strip()))

0       4
1      11
2       0
3       2
4       6
       ..
833     1
834     0
835     0
836     4
837     0
Name: 噓, Length: 838, dtype: int64

In [12]:
df["噓"].str.split(":").str[1].str.strip().astype(int)

0       4
1      11
2       0
3       2
4       6
       ..
833     1
834     0
835     0
836     4
837     0
Name: 噓, Length: 838, dtype: int64

In [13]:
df

,推,噓,分數,作者,標題,時間,score_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,21
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,0
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,20
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,29
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,100
...,...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,9
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,7
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,11
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,5

In [14]:
pd.to_datetime("20260815")

Timestamp('2026-08-15 00:00:00')

In [15]:
pd.to_datetime("2026-08-15 11:05")

Timestamp('2026-08-15 11:05:00')

In [16]:
pd.to_datetime("2026/08/15 11:05")

Timestamp('2026-08-15 11:05:00')

In [18]:
pd.to_datetime("2026-08-15 11:05")
pd.to_datetime("2026-08-15T11:05")

Timestamp('2026-08-15 11:05:00')

In [20]:
"""
時間: Wed Oct  7 21:27:26 2020
"""
pd.to_datetime("Wed Oct  7 21:27:26 2020")

Timestamp('2020-10-07 21:27:26')

In [21]:
df["時間"].str.replace("時間: ", "")

0      Fri Oct  2 13:56:39 2020
1      Wed Oct  7 18:53:08 2020
2      Fri Oct  2 13:30:55 2020
3      Fri Oct  2 12:35:18 2020
4      Fri Oct  2 13:43:25 2020
                 ...
833    Fri Oct  2 14:09:32 2020
834    Wed Oct  7 21:00:58 2020
835    Wed Oct  7 21:27:26 2020
836    Fri Oct  2 14:00:50 2020
837    Fri Oct  2 15:29:44 2020
Name: 時間, Length: 838, dtype: str

In [22]:
pd.to_datetime(df["時間"].str.replace("時間: ", ""))

0     2020-10-02 13:56:39
1     2020-10-07 18:53:08
2     2020-10-02 13:30:55
3     2020-10-02 12:35:18
4     2020-10-02 13:43:25
              ...
833   2020-10-02 14:09:32
834   2020-10-07 21:00:58
835   2020-10-07 21:27:26
836   2020-10-02 14:00:50
837   2020-10-02 15:29:44
Name: 時間, Length: 838, dtype: datetime64[us]

In [23]:
df["datetime_t"] = pd.to_datetime(df["時間"].str.replace("時間: ", ""))
df

,推,噓,分數,作者,標題,時間,score_t,datetime_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,21,2020-10-02 13:56:39
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,0,2020-10-07 18:53:08
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,20,2020-10-02 13:30:55
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,29,2020-10-02 12:35:18
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,100,2020-10-02 13:43:25
...,...,...,...,...,...,...,...,...
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,9,2020-10-02 14:09:32
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,7,2020-10-07 21:00:58
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0,2020-10-07 21:27:26
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,11,2020-10-02 14:00:50
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,5,2020-10-02 15:29:44

In [24]:
df["噓"].str.replace("噓: ", "")

0       4
1      11
2       0
3       2
4       6
       ..
833     1
834     0
835     0
836     4
837     0
Name: 噓, Length: 838, dtype: str

## Filter Data

In [25]:
df["datetime_t"] > pd.to_datetime("2020-10-05")

0      False
1       True
2      False
3      False
4      False
       ...
833    False
834     True
835     True
836    False
837    False
Name: datetime_t, Length: 838, dtype: bool

In [ ]:
"""
select * from df
where datetime_t > '2020-10-05'
"""
df[df["datetime_t"] > pd.to_datetime("2020-10-05")]

,推,噓,分數,作者,標題,時間,score_t,datetime_t
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,0,2020-10-07 18:53:08
7,2,噓: 4,分數: -2,作者: hk410050 (A柏),標題: [新聞] 國際藝文人士來台可申請專案縮短隔離 國,時間: Wed Oct 7 16:53:31 2020,-2,2020-10-07 16:53:31
8,36,噓: 4,分數: 32,作者: tennoji2003 (),標題: [問卦] 隨便說三個你會的做愛技巧！,時間: Wed Oct 7 17:55:20 2020,32,2020-10-07 17:55:20
11,7,噓: 2,分數: 5,作者: hhuuu (hhhh),標題: [問卦] 你第一眼直覺這個能防螞蟻嗎,時間: Wed Oct 7 17:30:27 2020,5,2020-10-07 17:30:27
12,149,噓: 14,分數: 135,作者: gogopacer (gogopacer),標題: [問卦] 大安區的便當這樣多少？,時間: Wed Oct 7 18:07:59 2020,135,2020-10-07 18:07:59
...,...,...,...,...,...,...,...,...
828,4,噓: 1,分數: 3,作者: autokey (該起床啦),標題: [問卦] 一天有10分鐘該訓練何種能力的八卦?,時間: Wed Oct 7 19:44:35 2020,3,2020-10-07 19:44:35
830,7,噓: 1,分數: 6,作者: MintSu (Simon),標題: [問卦] 中國功夫打的贏印度少林功夫嗎？,時間: Wed Oct 7 16:42:58 2020,6,2020-10-07 16:42:58
832,5,噓: 0,分數: 5,作者: doraBBO (天才小釣手),標題: [問卦] 為什麼要相信房子會跌不能買這種話？,時間: Wed Oct 7 19:37:00 2020,5,2020-10-07 19:37:00
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,7,2020-10-07 21:00:58
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0,2020-10-07 21:27:26

In [27]:
filter_score_gt_10 = df["score_t"] > 10
filter_score_lt_50 = df["score_t"] < 50

In [ ]:
"""
select * from df
where score_t > 10 and score_t < 50
"""
df[
    filter_score_gt_10 & filter_score_lt_50
]

,推,噓,分數,作者,標題,時間,score_t,datetime_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,21,2020-10-02 13:56:39
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,20,2020-10-02 13:30:55
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,29,2020-10-02 12:35:18
8,36,噓: 4,分數: 32,作者: tennoji2003 (),標題: [問卦] 隨便說三個你會的做愛技巧！,時間: Wed Oct 7 17:55:20 2020,32,2020-10-07 17:55:20
30,26,噓: 3,分數: 23,作者: jasonlin2100 (jasonlin),標題: [問卦] 湖口一堆流氓8+9？,時間: Wed Oct 7 18:39:50 2020,23,2020-10-07 18:39:50
...,...,...,...,...,...,...,...,...
808,29,噓: 6,分數: 23,作者: whj0530 (億載金城武),標題: [新聞] 川普夫婦確診陸網嗨爆！直衝微博熱搜第一,時間: Fri Oct 2 14:59:13 2020,23,2020-10-02 14:59:13
810,28,噓: 2,分數: 26,作者: hoyumi (正版型男...無誤!!!),標題: [新聞] 立院初審 調戲同性最高可處6000元罰鍰,時間: Wed Oct 7 17:29:05 2020,26,2020-10-07 17:29:05
822,63,噓: 21,分數: 42,作者: joug (好東西不簽嗎),標題: [新聞] 國防部：教召14天最高加薪1.5倍 1年1訓2,時間: Wed Oct 7 16:31:29 2020,42,2020-10-07 16:31:29
823,50,噓: 12,分數: 38,作者: q347 (我家隔壁北川景子),標題: [問卦] 兒子藏老媽食物被發現 老媽要不爽多久??,時間: Wed Oct 7 18:52:41 2020,38,2020-10-07 18:52:41
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,11,2020-10-02 14:00:50

In [30]:
filter_score_gt_10

0       True
1      False
2       True
3       True
4       True
       ...
833    False
834    False
835    False
836     True
837    False
Name: score_t, Length: 838, dtype: bool

In [31]:
filter_score_lt_50

0       True
1       True
2       True
3       True
4      False
       ...
833     True
834     True
835     True
836     True
837     True
Name: score_t, Length: 838, dtype: bool

In [33]:
"""
select * from df
where score_t < 10 or score_t > 50
"""
filter_score_gt_50 = df["score_t"] > 50
filter_score_lt_10 = df["score_t"] < 10
df[
    filter_score_gt_50 | filter_score_lt_10
]

,推,噓,分數,作者,標題,時間,score_t,datetime_t
1,11,噓: 11,分數: 0,作者: LoveMakeLove (ボケ),標題: [新聞]江啟臣：兩岸是不對稱的戰爭 從募兵改徵兵,時間: Wed Oct 7 18:53:08 2020,0,2020-10-07 18:53:08
4,106,噓: 6,分數: 100,作者: kasumi5566 (霞),標題: [問卦] 支那女生是不是都沒錢修補衣服,時間: Fri Oct 2 13:43:25 2020,100,2020-10-02 13:43:25
5,11,噓: 27,分數: -16,作者: starport (輕鬆看),標題: [新聞] 川普夫婦確診了！網友卻認為「案情不單,時間: Fri Oct 2 14:30:34 2020,-16,2020-10-02 14:30:34
6,6,噓: 0,分數: 6,作者: trolleybus99 (不要問),標題: [問卦] 習大大現在在想什麼,時間: Fri Oct 2 14:07:53 2020,6,2020-10-02 14:07:53
7,2,噓: 4,分數: -2,作者: hk410050 (A柏),標題: [新聞] 國際藝文人士來台可申請專案縮短隔離 國,時間: Wed Oct 7 16:53:31 2020,-2,2020-10-07 16:53:31
...,...,...,...,...,...,...,...,...
832,5,噓: 0,分數: 5,作者: doraBBO (天才小釣手),標題: [問卦] 為什麼要相信房子會跌不能買這種話？,時間: Wed Oct 7 19:37:00 2020,5,2020-10-07 19:37:00
833,10,噓: 1,分數: 9,作者: lockgolden (鎖金),標題: [問卦] PTT十年後會像無名小站那樣關閉嗎?,時間: Fri Oct 2 14:09:32 2020,9,2020-10-02 14:09:32
834,7,噓: 0,分數: 7,作者: nothisman (在人海中迷失),標題: [新聞] 地表「最胖肥熊」出爐！ 635kg棕熊挺「,時間: Wed Oct 7 21:00:58 2020,7,2020-10-07 21:00:58
835,0,噓: 0,分數: 0,作者: wa778895 (oilsunbright),標題: [問卦] 我是被下套了嗎？,時間: Wed Oct 7 21:27:26 2020,0,2020-10-07 21:27:26
837,5,噓: 0,分數: 5,作者: bigtreelife (Tree),標題: [問卦] 叫外送的年輕人都是什麼人,時間: Fri Oct 2 15:29:44 2020,5,2020-10-02 15:29:44

In [ ]:
"""
select * from df
where not (score_t < 10 or score_t > 50)
"""
df[
    ~(filter_score_gt_50 | filter_score_lt_10)
]

,推,噓,分數,作者,標題,時間,score_t,datetime_t
0,25,噓: 4,分數: 21,作者: Rusnake5566 (魯蛇+56 PTT最強帳號),標題: [問卦] 兩個候選人選前一個月同時陣亡的可能性,時間: Fri Oct 2 13:56:39 2020,21,2020-10-02 13:56:39
2,20,噓: 0,分數: 20,作者: MintSu (Simon),標題: [問卦] 如果川普老婆死於武漢肺炎會怎麼樣？,時間: Fri Oct 2 13:30:55 2020,20,2020-10-02 13:30:55
3,31,噓: 2,分數: 29,作者: seiya2000 (風見),標題: [問卦] 為什麼古代生物體型可以長到這麼大？,時間: Fri Oct 2 12:35:18 2020,29,2020-10-02 12:35:18
8,36,噓: 4,分數: 32,作者: tennoji2003 (),標題: [問卦] 隨便說三個你會的做愛技巧！,時間: Wed Oct 7 17:55:20 2020,32,2020-10-07 17:55:20
14,10,噓: 0,分數: 10,作者: ccf52881 (ccf52881),標題: [新聞] 新莊、樹林周邊電桿全面地下化 耗資9億54,時間: Wed Oct 7 16:42:00 2020,10,2020-10-07 16:42:00
...,...,...,...,...,...,...,...,...
808,29,噓: 6,分數: 23,作者: whj0530 (億載金城武),標題: [新聞] 川普夫婦確診陸網嗨爆！直衝微博熱搜第一,時間: Fri Oct 2 14:59:13 2020,23,2020-10-02 14:59:13
810,28,噓: 2,分數: 26,作者: hoyumi (正版型男...無誤!!!),標題: [新聞] 立院初審 調戲同性最高可處6000元罰鍰,時間: Wed Oct 7 17:29:05 2020,26,2020-10-07 17:29:05
822,63,噓: 21,分數: 42,作者: joug (好東西不簽嗎),標題: [新聞] 國防部：教召14天最高加薪1.5倍 1年1訓2,時間: Wed Oct 7 16:31:29 2020,42,2020-10-07 16:31:29
823,50,噓: 12,分數: 38,作者: q347 (我家隔壁北川景子),標題: [問卦] 兒子藏老媽食物被發現 老媽要不爽多久??,時間: Wed Oct 7 18:52:41 2020,38,2020-10-07 18:52:41
836,15,噓: 4,分數: 11,作者: stan0720 (Kimo),標題: [問卦] 認真問 人一天可以走幾公里呀？,時間: Fri Oct 2 14:00:50 2020,11,2020-10-02 14:00:50