In [1]:
import pandas as pd

In [2]:
file_path = "holding.parquet"
df = pd.read_parquet(file_path)
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
13461477,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
13461478,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
13461479,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [ ]:
"""
select distinct portno
from df;

select count(distinct(portno)) from df;
"""
df["portno"].unique()

<ArrowStringArray>
['2998623', '2998638', '2998809', '2998821', '3000255', '300035d', '3001404',
 '3002313', '3002316', '300251d',
 ...
 '3156837', '3156924', '3157206', '3157233', '315723c', '3157245', '315724b',
 '315724e', '3157332', '3157350']
Length: 9453, dtype: str

In [6]:
"""
select
    portno,
    count(1)
from df
group by portno;
"""
df.groupby(["portno"], as_index=False).size()

       portno  size
0     2998623  3114
1     2998638   853
2     2998809   276
3     2998821   629
4     2998923   385
...       ...   ...
9448  3157308   241
9449  315732c    32
9450  3157332   506
9451  315733b    16
9452  3157350   428

[9453 rows x 2 columns]

In [ ]:
df.groupby(
    ["portno"], as_index=False,
).agg(
    portno_count=("portno", "size"),
    share_sum=("nbr_shares", "sum"),
)

       portno  portno_count     share_sum
0     2998623          3114  4.002971e+10
1     2998638           853  3.403148e+09
2     2998809           276  1.017395e+09
3     2998821           629  9.877622e+08
4     2998923           385  1.723861e+08
...       ...           ...           ...
9448  3157308           241  2.708380e+05
9449  315732c            32 -6.196600e+04
9450  3157332           506  3.783357e+08
9451  315733b            16  1.783122e+07
9452  3157350           428  1.927648e+07

[9453 rows x 3 columns]

In [12]:
"""
select
    portno,
    sum(percent_tna) as perc
from df
group by portno, eff_dt
"""
df.groupby(
    ["portno", "eff_dt"],
    as_index=False,
).agg(
    perc_123=("percent_tna", "sum")
)

        portno      eff_dt  perc_123
0      2998623  2021/01/08     99.79
1      2998623  2021/02/05     99.20
2      2998623  2021/05/10     99.96
3      2998623  2021/06/07     99.93
4      2998623  2021/08/09     99.78
...        ...         ...       ...
59334  3157308  2021/12/07    100.23
59335  315732c  2021/12/07    100.12
59336  3157332  2021/12/21     99.94
59337  315733b  2021/12/07     99.73
59338  3157350  2021/12/21     99.55

[59339 rows x 3 columns]

In [21]:
df.groupby(
    ["portno", "eff_dt"],
    as_index=False,
)["percent_tna"].sum().rename(
    columns={"percent_tna": "new_percent_tna"}
)

        portno      eff_dt  new_percent_tna
0      2998623  2021/01/08            99.79
1      2998623  2021/02/05            99.20
2      2998623  2021/05/10            99.96
3      2998623  2021/06/07            99.93
4      2998623  2021/08/09            99.78
...        ...         ...              ...
59334  3157308  2021/12/07           100.23
59335  315732c  2021/12/07           100.12
59336  3157332  2021/12/21            99.94
59337  315733b  2021/12/07            99.73
59338  3157350  2021/12/21            99.55

[59339 rows x 3 columns]

In [ ]:
"""
select
    portno,
    report_dt
from df
"""
df[
    [
        "portno",
        "report_dt",
    ]
]

           portno   report_dt
0         2998623  2020/11/30
1         2998623  2020/11/30
2         2998623  2020/11/30
3         2998623  2020/11/30
4         2998623  2020/11/30
...           ...         ...
13461477  3157350  2021/11/30
13461478  3157350  2021/11/30
13461479  3157350  2021/11/30
13461480  3157350  2021/11/30
13461481  3157350  2021/11/30

[13461482 rows x 2 columns]

In [ ]:
"""
select * from df limit 2
"""
df.head(2)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610

In [ ]:
"""
offset
"""
df.tail(2)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
13461480,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
13461481,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [ ]:
"""
select
    portno,
    sum(percent_tna) as perc
from df
group by portno, eff_dt
order by portno asc, eff_dt desc;
"""
df.groupby(
    ["portno", "eff_dt"],
    as_index=False,
).agg(
    perc_123=("percent_tna", "sum")
).sort_values(["portno", "eff_dt"], ascending=[True, False])

        portno      eff_dt  perc_123
8      2998623  2021/12/07     99.90
7      2998623  2021/11/05     99.83
6      2998623  2021/10/07     99.63
5      2998623  2021/09/07     99.88
4      2998623  2021/08/09     99.78
...        ...         ...       ...
59334  3157308  2021/12/07    100.23
59335  315732c  2021/12/07    100.12
59336  3157332  2021/12/21     99.94
59337  315733b  2021/12/07     99.73
59338  3157350  2021/12/21     99.55

[59339 rows x 3 columns]

In [31]:
df[1:4]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,241240438.4,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,229683610.8,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,213250339.5,PHILIP MORRIS INTERNATIONAL INC,71817210

In [32]:
df.loc[1:4]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [34]:
df.loc[[1, 3, 5, 7], ["portno", "report_dt", "security_rank"]]

    portno   report_dt  security_rank
1  2998623  2020/11/30              2
3  2998623  2020/11/30              4
5  2998623  2020/11/30              6
7  2998623  2020/11/30              8

In [35]:
df.iloc[[1, 3, 5, 7], [1, 3, 5]]

    report_dt      eff_dt  nbr_shares
1  2020/11/30  2021/01/08   3087680.0
3  2020/11/30  2021/01/08   2815186.0
5  2020/11/30  2021/01/08    866386.0
7  2020/11/30  2021/01/08   5045923.0

In [36]:
df.describe()

       security_rank   percent_tna    nbr_shares    market_val
count   1.346148e+07  1.346148e+07  1.346148e+07  1.346148e+07
mean    5.865976e+02  4.404682e-01  2.438436e+07  1.137428e+07
std     8.539445e+02  2.125681e+00  6.523191e+09  1.651424e+08
min     1.000000e+00 -2.489000e+02 -1.027540e+12 -6.520285e+09
25%     8.200000e+01  2.000000e-02  5.744000e+03  1.153754e+05
50%     2.750000e+02  8.000000e-02  5.249300e+04  6.464532e+05
75%     7.270000e+02  3.100000e-01  4.488590e+05  3.176073e+06
max     8.716000e+03  3.028200e+02  6.667220e+12  7.118158e+10