In [1]:
import pandas as pd

df = pd.read_csv("employees.csv")
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White          NaN  68000.0  carol.white@company.com
3        E004          NaN          NaN  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN          NaN      NaN                      NaN

In [2]:
type(None)

NoneType

In [3]:
df["name"][5]

nan

In [4]:
type(df["name"][5])

float

In [5]:
"""
select avg(salary) from df;
"""
df["salary"].mean()

np.float64(72500.0)

In [6]:
df["salary"].fillna(0)

0    95000.0
1    72000.0
2    68000.0
3    55000.0
4        0.0
5        0.0
Name: salary, dtype: float64

In [7]:
df["salary"].fillna(0).mean()

np.float64(48333.333333333336)

In [8]:
df["department"].ffill()

0    Engineering
1      Marketing
2      Marketing
3      Marketing
4          Sales
5          Sales
Name: department, dtype: str

In [9]:
df["department"] = df["department"].ffill()
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White    Marketing  68000.0  carol.white@company.com
3        E004          NaN    Marketing  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN        Sales      NaN                      NaN

In [10]:
df["email"].fillna("N/A")

0     alice.chen@company.com
1                        N/A
2    carol.white@company.com
3                        N/A
4    eve.johnson@company.com
5                        N/A
Name: email, dtype: str

In [11]:
df.isna()

   employee_id   name  department  salary  email
0        False  False       False   False  False
1        False  False       False   False   True
2        False  False       False   False  False
3        False   True       False   False   True
4        False  False       False    True  False
5        False   True       False    True   True

In [12]:
df["name"].isna()

0    False
1    False
2    False
3     True
4    False
5     True
Name: name, dtype: bool

In [13]:
# ~(df["name"].isna())
df["name"].notna()

0     True
1     True
2     True
3    False
4     True
5    False
Name: name, dtype: bool

In [14]:
df[df["name"].notna()]

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White    Marketing  68000.0  carol.white@company.com
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com

In [15]:
df

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White    Marketing  68000.0  carol.white@company.com
3        E004          NaN    Marketing  55000.0                      NaN
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com
5        E006          NaN        Sales      NaN                      NaN

In [17]:
df.dropna(thresh=4)

  employee_id         name   department   salary                    email
0        E001   Alice Chen  Engineering  95000.0   alice.chen@company.com
1        E002    Bob Smith    Marketing  72000.0                      NaN
2        E003  Carol White    Marketing  68000.0  carol.white@company.com
4        E005  Eve Johnson        Sales      NaN  eve.johnson@company.com