In [1]:
import pandas as pd

In [2]:
path_staff_detail_different_col = "staff_detail_different_col.csv"
path_staff_detail = "staff_detail.csv"
path_staff_samecol = "staff_samecol.csv"
path_staff = "staff.csv"

df_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)
df_staff_detail = pd.read_csv(path_staff_detail)
df_staff_samecol = pd.read_csv(path_staff_samecol)
df_staff = pd.read_csv(path_staff)

In [3]:
df_staff

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000

In [4]:
df_staff_detail

    ID Level  UpdateDate
0    1     A  2019-08-09
1    1     S  2020-12-08
2    2     A  2021-05-30
3    3     A  2018-03-26
4    3     S  2020-12-08
5    4     A  2022-05-02
6    5     A  2019-11-05
7    5     S  2022-04-25
8    6     A  2022-03-03
9    7     A  2017-03-29
10   7     S  2018-05-02
11   7     M  2021-09-01
12   8     A  2018-11-26
13   8     S  2020-03-15
14   8     M  2022-05-03

In [5]:
df_staff_detail.merge(df_staff)

    ID Level  UpdateDate   Name  DeptId  Age Gender  Salary
0    1     A  2019-08-09   Mike       2   45      M   60000
1    1     S  2020-12-08   Mike       2   45      M   60000
2    2     A  2021-05-30   Judy       2   30      F   48000
3    3     A  2018-03-26  Allen       1   22      M   50000
4    3     S  2020-12-08  Allen       1   22      M   50000
5    4     A  2022-05-02    Tom       2   47      M   47000
6    5     A  2019-11-05   Jack       3   36      M   52000
7    5     S  2022-04-25   Jack       3   36      M   52000
8    6     A  2022-03-03   Abby       2   24      F   45000
9    7     A  2017-03-29  Trump       1   80      M   80000
10   7     S  2018-05-02  Trump       1   80      M   80000
11   7     M  2021-09-01  Trump       1   80      M   80000
12   8     A  2018-11-26  Marry       3   29      F   87000
13   8     S  2020-03-15  Marry       3   29      F   87000
14   8     M  2022-05-03  Marry       3   29      F   87000

In [7]:
"""
select *
from df_staff_detail
left join df_staff
on df_staff_detail.ID = df_staff.ID
"""
df_staff_detail.merge(
    df_staff,
    how="left",
    left_on="ID",
    right_on="ID",
)

    ID Level  UpdateDate   Name  DeptId  Age Gender  Salary
0    1     A  2019-08-09   Mike       2   45      M   60000
1    1     S  2020-12-08   Mike       2   45      M   60000
2    2     A  2021-05-30   Judy       2   30      F   48000
3    3     A  2018-03-26  Allen       1   22      M   50000
4    3     S  2020-12-08  Allen       1   22      M   50000
5    4     A  2022-05-02    Tom       2   47      M   47000
6    5     A  2019-11-05   Jack       3   36      M   52000
7    5     S  2022-04-25   Jack       3   36      M   52000
8    6     A  2022-03-03   Abby       2   24      F   45000
9    7     A  2017-03-29  Trump       1   80      M   80000
10   7     S  2018-05-02  Trump       1   80      M   80000
11   7     M  2021-09-01  Trump       1   80      M   80000
12   8     A  2018-11-26  Marry       3   29      F   87000
13   8     S  2020-03-15  Marry       3   29      F   87000
14   8     M  2022-05-03  Marry       3   29      F   87000

   ID   Name  DeptId  Age Gender  Salary  UpdateDate
0   1   Mike       2   45      M   60000  2020-12-08
1   2   Judy       2   30      F   48000  2021-05-30
2   3  Allen       1   22      M   50000  2020-12-08
3   4    Tom       2   47      M   47000  2022-05-02
4   5   Jack       3   36      M   52000  2022-04-25
5   6   Abby       2   24      F   45000  2022-03-03
6   7  Trump       1   80      M   80000  2021-09-01
7   8  Marry       3   29      F   87000  2022-05-03

In [9]:
df_staff_detail_different_col

    EmpNum Level  UpdateDate
0        1     A  2019-08-09
1        1     S  2020-12-08
2        2     A  2021-05-30
3        3     A  2018-03-26
4        3     S  2020-12-08
5        4     A  2022-05-02
6        5     A  2019-11-05
7        5     S  2022-04-25
8        6     A  2022-03-03
9        7     A  2017-03-29
10       7     S  2018-05-02
11       7     M  2021-09-01
12       8     A  2018-11-26
13       8     S  2020-03-15
14       8     M  2022-05-03

In [11]:
"""
select *
from df_staff_detail_different_col
left join df_staff
on df_staff_detail_different_col.EmpNum = df_staff.ID
"""
df_staff_detail_different_col.merge(
    df_staff,
    how="left",
    left_on="EmpNum",
    right_on="ID",
)

    EmpNum Level  UpdateDate  ID   Name  DeptId  Age Gender  Salary
0        1     A  2019-08-09   1   Mike       2   45      M   60000
1        1     S  2020-12-08   1   Mike       2   45      M   60000
2        2     A  2021-05-30   2   Judy       2   30      F   48000
3        3     A  2018-03-26   3  Allen       1   22      M   50000
4        3     S  2020-12-08   3  Allen       1   22      M   50000
5        4     A  2022-05-02   4    Tom       2   47      M   47000
6        5     A  2019-11-05   5   Jack       3   36      M   52000
7        5     S  2022-04-25   5   Jack       3   36      M   52000
8        6     A  2022-03-03   6   Abby       2   24      F   45000
9        7     A  2017-03-29   7  Trump       1   80      M   80000
10       7     S  2018-05-02   7  Trump       1   80      M   80000
11       7     M  2021-09-01   7  Trump       1   80      M   80000
12       8     A  2018-11-26   8  Marry       3   29      F   87000
13       8     S  2020-03-15   8  Marry       3   29      F   87000
14       8     M  2022-05-03   8  Marry       3   29      F   87000

In [ ]:
"""
select
    df_staff_detail_different_col.UpdateDate as UpdateDate_detail,
    df_staff.UpdateDate as UpdateDate_staff,
    ...
from df_staff_detail_different_col
left join df_staff
on df_staff_detail_different_col.EmpNum = df_staff.ID
"""
df_staff_detail_different_col.merge(
    df_staff_samecol,
    how="left",
    left_on="EmpNum",
    right_on="ID",
    suffixes=["_detail", "_staff"]
)

,EmpNum,Level,UpdateDate_detail,ID,Name,DeptId,Age,Gender,Salary,UpdateDate_staff
0,1,A,2019-08-09,1,Mike,2,45,M,60000,2020-12-08
1,1,S,2020-12-08,1,Mike,2,45,M,60000,2020-12-08
2,2,A,2021-05-30,2,Judy,2,30,F,48000,2021-05-30
3,3,A,2018-03-26,3,Allen,1,22,M,50000,2020-12-08
4,3,S,2020-12-08,3,Allen,1,22,M,50000,2020-12-08
5,4,A,2022-05-02,4,Tom,2,47,M,47000,2022-05-02
6,5,A,2019-11-05,5,Jack,3,36,M,52000,2022-04-25
7,5,S,2022-04-25,5,Jack,3,36,M,52000,2022-04-25
8,6,A,2022-03-03,6,Abby,2,24,F,45000,2022-03-03
9,7,A,2017-03-29,7,Trump,1,80,M,80000,2021-09-01
10,7,S,2018-05-02,7,Trump,1,80,M,80000,2021-09-01
11,7,M,2021-09-01,7,Trump,1,80,M,80000,2021-09-01
12,8,A,2018-11-26,8,Marry,3,29,F,87000,2022-05-03
13,8,S,2020-03-15,8,Marry,3,29,F,87000,2022-05-03
14,8,M,2022-05-03,8,Marry,3,29,F,87000,2022-05-03

## SQL UNION

In [15]:
import pandas as pd

df = pd.DataFrame(
    data=[
        ["Allen", 175, 22],
        ["Ted", 180, 25]
    ],
    columns=["Name", "Height", "Age"]
)

df_1 = pd.DataFrame(
    data=[
        ["Jake", 177, 28],
        ["Mary", 170, 24]
    ],
    columns=["Name", "Height", "Age"]
)

In [17]:
pd.concat(
    [df, df_1],
    ignore_index=True,
)

    Name  Height  Age
0  Allen     175   22
1    Ted     180   25
2   Jake     177   28
3   Mary     170   24

In [ ]:
"""
select * from df
union
select * from df_1
"""
df_concat = pd.concat(
    [df, df_1],
    ignore_index=True,
)
df_concat

    Name  Height  Age
0  Allen     175   22
1    Ted     180   25
2   Jake     177   28
3   Mary     170   24

In [19]:
df_concat.drop_duplicates()

    Name  Height  Age
0  Allen     175   22
1    Ted     180   25
2   Jake     177   28
3   Mary     170   24

In [ ]:
# Drop duplicates by specific columns
df_concat.drop_duplicates(["Name", "Height"])

    Name  Height  Age
0  Allen     175   22
1    Ted     180   25
2   Jake     177   28
3   Mary     170   24