In [1]:
import pandas as pd

data = {
    "date": ["2023-04-01", "2023-04-01", "2023-04-01", "2023-04-02", "2023-04-02", "2023-04-03", "2023-04-03"],
    "product": ["Apple", "Banana", "Apple", "Banana", "Banana", "Apple", "Banana"],
    "sales": [100, 200, 150, 100, 150, 200, 180]
}

df = pd.DataFrame(data)

In [2]:
df

         date product  sales
0  2023-04-01   Apple    100
1  2023-04-01  Banana    200
2  2023-04-01   Apple    150
3  2023-04-02  Banana    100
4  2023-04-02  Banana    150
5  2023-04-03   Apple    200
6  2023-04-03  Banana    180

In [3]:
df.sort_values(["date", "sales"], ascending=False)

         date product  sales
5  2023-04-03   Apple    200
6  2023-04-03  Banana    180
4  2023-04-02  Banana    150
3  2023-04-02  Banana    100
1  2023-04-01  Banana    200
2  2023-04-01   Apple    150
0  2023-04-01   Apple    100

In [4]:
df_sorted = df.sort_values(["date", "sales"], ascending=False)
df_sorted

         date product  sales
5  2023-04-03   Apple    200
6  2023-04-03  Banana    180
4  2023-04-02  Banana    150
3  2023-04-02  Banana    100
1  2023-04-01  Banana    200
2  2023-04-01   Apple    150
0  2023-04-01   Apple    100

In [6]:
df_sorted.groupby(["date", "product"]).cumcount() + 1

5    1
6    1
4    1
3    2
1    1
2    1
0    2
dtype: int64

In [7]:
df_sorted["row_number"] = df_sorted.groupby(["date", "product"]).cumcount() + 1
df_sorted

         date product  sales  row_number
5  2023-04-03   Apple    200           1
6  2023-04-03  Banana    180           1
4  2023-04-02  Banana    150           1
3  2023-04-02  Banana    100           2
1  2023-04-01  Banana    200           1
2  2023-04-01   Apple    150           1
0  2023-04-01   Apple    100           2

In [9]:
df_sorted[
    df_sorted["row_number"] == 1
][
    [
        "date",
        "product",
        "sales",
    ]
]

         date product  sales
5  2023-04-03   Apple    200
6  2023-04-03  Banana    180
4  2023-04-02  Banana    150
1  2023-04-01  Banana    200
2  2023-04-01   Apple    150