In [1]:
import pandas as pd
from pandasql import sqldf

In [2]:
path_staff_detail_different_col = "staff_detail_different_col.csv"
path_staff_detail = "staff_detail.csv"
path_staff_samecol = "staff_samecol.csv"
path_staff = "staff.csv"

df_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)
df_staff_detail = pd.read_csv(path_staff_detail)
df_staff_samecol = pd.read_csv(path_staff_samecol)
df_staff = pd.read_csv(path_staff)

In [3]:
sql = "select * from df_staff"
sqldf(sql)

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000

In [ ]:
"""
df_staff[
    df_staff["Salary"] > 5000
]
"""
sql = "select * from df_staff where Salary > 50000"
sqldf(sql)

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   5   Jack       3   36      M   52000
2   7  Trump       1   80      M   80000
3   8  Marry       3   29      F   87000

In [5]:
globals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import pandas as pd\nfrom pandasql import sqldf',
  'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
  'sql = "select * from df_staff"\nsqldf(sql)',
  'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
  'globals()'],
 '_oh': {3:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000,
  4:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   5   Jack       3   36      M   52000
  2   7  Trump       1   80      M   80000
  3   8  Marry       3   29      F   87000},
 '_dh': [PosixPath('/Users/uuboy.scy/side-project/tibame/tkr102/pandas-practice')],
 'In': ['',
  'import pandas as pd\nfrom pandasql import sqldf',
  'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
  'sql = "select * from df_staff"\nsqldf(sql)',
  'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
  'globals()'],
 'Out': {3:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000,
  4:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   5   Jack       3   36      M   52000
  2   7  Trump       1   80      M   80000
  3   8  Marry       3   29      F   87000},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10831cec0>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x10831eba0>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x10831eba0>,
 'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   5   Jack       3   36      M   52000
 2   7  Trump       1   80      M   80000
 3   8  Marry       3   29      F   87000,
 '__':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '___': '',
 '__vsc_ipynb_file__': '/Users/uuboy.scy/side-project/tibame/tkr102/pandas-practice/10_pandasql.ipynb',
 '_i': 'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
 '_ii': 'sql = "select * from df_staff"\nsqldf(sql)',
 '_iii': 'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
 '_i1': 'import pandas as pd\nfrom pandasql import sqldf',
 'pd': <module 'pandas' from '/Users/uuboy.scy/side-project/tibame/tkr102/pandas-practice/.venv/lib/python3.14/site-packages/pandas/__init__.py'>,
 'sqldf': <function pandasql.sqldf.sqldf(query, env=None, db_uri='sqlite:///:memory:')>,
 '_i2': 'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
 'path_staff_detail_different_col': 'staff_detail_different_col.csv',
 'path_staff_detail': 'staff_detail.csv',
 'path_staff_samecol': 'staff_samecol.csv',
 'path_staff': 'staff.csv',
 'df_staff_detail_different_col':     EmpNum Level  UpdateDate
 0        1     A  2019-08-09
 1        1     S  2020-12-08
 2        2     A  2021-05-30
 3        3     A  2018-03-26
 4        3     S  2020-12-08
 5        4     A  2022-05-02
 6        5     A  2019-11-05
 7        5     S  2022-04-25
 8        6     A  2022-03-03
 9        7     A  2017-03-29
 10       7     S  2018-05-02
 11       7     M  2021-09-01
 12       8     A  2018-11-26
 13       8     S  2020-03-15
 14       8     M  2022-05-03,
 'df_staff_detail':     ID Level  UpdateDate
 0    1     A  2019-08-09
 1    1     S  2020-12-08
 2    2     A  2021-05-30
 3    3     A  2018-03-26
 4    3     S  2020-12-08
 5    4     A  2022-05-02
 6    5     A  2019-11-05
 7    5     S  2022-04-25
 8    6     A  2022-03-03
 9    7     A  2017-03-29
 10   7     S  2018-05-02
 11   7     M  2021-09-01
 12   8     A  2018-11-26
 13   8     S  2020-03-15
 14   8     M  2022-05-03,
 'df_staff_samecol':    ID   Name  DeptId  Age Gender  Salary  UpdateDate
 0   1   Mike       2   45      M   60000  2020-12-08
 1   2   Judy       2   30      F   48000  2021-05-30
 2   3  Allen       1   22      M   50000  2020-12-08
 3   4    Tom       2   47      M   47000  2022-05-02
 4   5   Jack       3   36      M   52000  2022-04-25
 5   6   Abby       2   24      F   45000  2022-03-03
 6   7  Trump       1   80      M   80000  2021-09-01
 7   8  Marry       3   29      F   87000  2022-05-03,
 'df_staff':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i3': 'sql = "select * from df_staff"\nsqldf(sql)',
 'sql': 'select * from df_staff where Salary > 50000',
 '_3':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i4': 'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
 '_4':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   5   Jack       3   36      M   52000
 2   7  Trump       1   80      M   80000
 3   8  Marry       3   29      F   87000,
 '_i5': 'globals()'}

In [6]:
globals()["df_staff"]

   ID   Name  DeptId  Age Gender  Salary
0   1   Mike       2   45      M   60000
1   2   Judy       2   30      F   48000
2   3  Allen       1   22      M   50000
3   4    Tom       2   47      M   47000
4   5   Jack       3   36      M   52000
5   6   Abby       2   24      F   45000
6   7  Trump       1   80      M   80000
7   8  Marry       3   29      F   87000

In [7]:
locals()

{'__name__': '__main__',
 '__doc__': 'Automatically created module for IPython interactive environment',
 '__package__': None,
 '__loader__': None,
 '__spec__': None,
 '__builtin__': <module 'builtins' (built-in)>,
 '__builtins__': <module 'builtins' (built-in)>,
 '_ih': ['',
  'import pandas as pd\nfrom pandasql import sqldf',
  'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
  'sql = "select * from df_staff"\nsqldf(sql)',
  'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
  'globals()',
  'globals()["df_staff"]',
  'locals()'],
 '_oh': {3:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000,
  4:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   5   Jack       3   36      M   52000
  2   7  Trump       1   80      M   80000
  3   8  Marry       3   29      F   87000,
  5: {...},
  6:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000},
 '_dh': [PosixPath('/Users/uuboy.scy/side-project/tibame/tkr102/pandas-practice')],
 'In': ['',
  'import pandas as pd\nfrom pandasql import sqldf',
  'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
  'sql = "select * from df_staff"\nsqldf(sql)',
  'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
  'globals()',
  'globals()["df_staff"]',
  'locals()'],
 'Out': {3:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000,
  4:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   5   Jack       3   36      M   52000
  2   7  Trump       1   80      M   80000
  3   8  Marry       3   29      F   87000,
  5: {...},
  6:    ID   Name  DeptId  Age Gender  Salary
  0   1   Mike       2   45      M   60000
  1   2   Judy       2   30      F   48000
  2   3  Allen       1   22      M   50000
  3   4    Tom       2   47      M   47000
  4   5   Jack       3   36      M   52000
  5   6   Abby       2   24      F   45000
  6   7  Trump       1   80      M   80000
  7   8  Marry       3   29      F   87000},
 'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x10831cec0>>,
 'exit': <IPython.core.autocall.ZMQExitAutocall at 0x10831eba0>,
 'quit': <IPython.core.autocall.ZMQExitAutocall at 0x10831eba0>,
 'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
 '_':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '__': {...},
 '___':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   5   Jack       3   36      M   52000
 2   7  Trump       1   80      M   80000
 3   8  Marry       3   29      F   87000,
 '__vsc_ipynb_file__': '/Users/uuboy.scy/side-project/tibame/tkr102/pandas-practice/10_pandasql.ipynb',
 '_i': 'globals()["df_staff"]',
 '_ii': 'globals()',
 '_iii': 'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
 '_i1': 'import pandas as pd\nfrom pandasql import sqldf',
 'pd': <module 'pandas' from '/Users/uuboy.scy/side-project/tibame/tkr102/pandas-practice/.venv/lib/python3.14/site-packages/pandas/__init__.py'>,
 'sqldf': <function pandasql.sqldf.sqldf(query, env=None, db_uri='sqlite:///:memory:')>,
 '_i2': 'path_staff_detail_different_col = "staff_detail_different_col.csv"\npath_staff_detail = "staff_detail.csv"\npath_staff_samecol = "staff_samecol.csv"\npath_staff = "staff.csv"\n\ndf_staff_detail_different_col = pd.read_csv(path_staff_detail_different_col)\ndf_staff_detail = pd.read_csv(path_staff_detail)\ndf_staff_samecol = pd.read_csv(path_staff_samecol)\ndf_staff = pd.read_csv(path_staff)',
 'path_staff_detail_different_col': 'staff_detail_different_col.csv',
 'path_staff_detail': 'staff_detail.csv',
 'path_staff_samecol': 'staff_samecol.csv',
 'path_staff': 'staff.csv',
 'df_staff_detail_different_col':     EmpNum Level  UpdateDate
 0        1     A  2019-08-09
 1        1     S  2020-12-08
 2        2     A  2021-05-30
 3        3     A  2018-03-26
 4        3     S  2020-12-08
 5        4     A  2022-05-02
 6        5     A  2019-11-05
 7        5     S  2022-04-25
 8        6     A  2022-03-03
 9        7     A  2017-03-29
 10       7     S  2018-05-02
 11       7     M  2021-09-01
 12       8     A  2018-11-26
 13       8     S  2020-03-15
 14       8     M  2022-05-03,
 'df_staff_detail':     ID Level  UpdateDate
 0    1     A  2019-08-09
 1    1     S  2020-12-08
 2    2     A  2021-05-30
 3    3     A  2018-03-26
 4    3     S  2020-12-08
 5    4     A  2022-05-02
 6    5     A  2019-11-05
 7    5     S  2022-04-25
 8    6     A  2022-03-03
 9    7     A  2017-03-29
 10   7     S  2018-05-02
 11   7     M  2021-09-01
 12   8     A  2018-11-26
 13   8     S  2020-03-15
 14   8     M  2022-05-03,
 'df_staff_samecol':    ID   Name  DeptId  Age Gender  Salary  UpdateDate
 0   1   Mike       2   45      M   60000  2020-12-08
 1   2   Judy       2   30      F   48000  2021-05-30
 2   3  Allen       1   22      M   50000  2020-12-08
 3   4    Tom       2   47      M   47000  2022-05-02
 4   5   Jack       3   36      M   52000  2022-04-25
 5   6   Abby       2   24      F   45000  2022-03-03
 6   7  Trump       1   80      M   80000  2021-09-01
 7   8  Marry       3   29      F   87000  2022-05-03,
 'df_staff':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i3': 'sql = "select * from df_staff"\nsqldf(sql)',
 'sql': 'select * from df_staff where Salary > 50000',
 '_3':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i4': 'sql = "select * from df_staff where Salary > 50000"\nsqldf(sql)',
 '_4':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   5   Jack       3   36      M   52000
 2   7  Trump       1   80      M   80000
 3   8  Marry       3   29      F   87000,
 '_i5': 'globals()',
 '_5': {...},
 '_i6': 'globals()["df_staff"]',
 '_6':    ID   Name  DeptId  Age Gender  Salary
 0   1   Mike       2   45      M   60000
 1   2   Judy       2   30      F   48000
 2   3  Allen       1   22      M   50000
 3   4    Tom       2   47      M   47000
 4   5   Jack       3   36      M   52000
 5   6   Abby       2   24      F   45000
 6   7  Trump       1   80      M   80000
 7   8  Marry       3   29      F   87000,
 '_i7': 'locals()'}

## Select the highest price of each author. All fields should be kept in the result table.

In [8]:
columns = ["article", "author", "price"]
data = [
    ["0001", "B", 3.99],
    ["0002", "A", 10.99],
    ["0003", "C", 1.69],
    ["0004", "B", 19.95],
    ["0005", "A", 6.96],
]
prticle_price_df = pd.DataFrame(data=data, columns=columns)
prticle_price_df

  article author  price
0    0001      B   3.99
1    0002      A  10.99
2    0003      C   1.69
3    0004      B  19.95
4    0005      A   6.96

In [10]:
prticle_price_df.groupby("author").cumcount()

0    0
1    0
2    0
3    1
4    1
dtype: int64

In [9]:
sorted_prticle_price_df = (
    prticle_price_df
    .sort_values(
        ["author", "price"],
        ascending=False,
    )
)
sorted_prticle_price_df

  article author  price
2    0003      C   1.69
3    0004      B  19.95
0    0001      B   3.99
1    0002      A  10.99
4    0005      A   6.96

In [13]:
sorted_prticle_price_df["row_num"] = (
    sorted_prticle_price_df
    .groupby("author")
    .cumcount() + 1
)
sorted_prticle_price_df[
    sorted_prticle_price_df["row_num"] == 1
].drop("row_num", axis=1)

  article author  price
2    0003      C   1.69
3    0004      B  19.95
1    0002      A  10.99

In [18]:
sql = """
    select
        *,
        max(price)
    from prticle_price_df
    group by author
"""
sqldf(sql)

  article author  price  max(price)
0    0002      A  10.99       10.99
1    0004      B  19.95       19.95
2    0003      C   1.69        1.69

In [17]:
sql = """
    select
        author,
        max(price)
    from prticle_price_df
    group by author
"""
sqldf(sql)

  author  max(price)
0      A       10.99
1      B       19.95
2      C        1.69

In [20]:
sql = """
    with tmp_df as (
        select
            *,
            ROW_NUMBER() over (partition by author order by price desc) as row_num
        from prticle_price_df
    )
    select
        article,
        author,
        price
    from tmp_df where row_num = 1
 """
sqldf(sql)

  article author  price
0    0002      A  10.99
1    0004      B  19.95
2    0003      C   1.69

In [ ]:
sql = """
select
    *,
    ROW_NUMBER() over (partition by author order by price desc) as row_num
from prticle_price_df
where row_num = 1
"""