In [3]:
import pandas as pd

data = {
    "date": ["2023-01-01", "2023-01-02", "2023-01-03", "2023-01-04", "2023-01-05"],
    "sales": [100, 200, 150, 300, 250]
}

df = pd.DataFrame(data)
df

         date  sales
0  2023-01-01    100
1  2023-01-02    200
2  2023-01-03    150
3  2023-01-04    300
4  2023-01-05    250

In [5]:
# 3-day rolling mean
df["rolling_mean"] = df["sales"].rolling(window=3).mean()
df

         date  sales  rolling_mean
0  2023-01-01    100           NaN
1  2023-01-02    200           NaN
2  2023-01-03    150    150.000000
3  2023-01-04    300    216.666667
4  2023-01-05    250    233.333333

In [6]:
df["rolling_mean"] = df["sales"].rolling(window=3, min_periods=1).mean()
df

         date  sales  rolling_mean
0  2023-01-01    100    100.000000
1  2023-01-02    200    150.000000
2  2023-01-03    150    150.000000
3  2023-01-04    300    216.666667
4  2023-01-05    250    233.333333