In [2]:
from urllib.parse import quote_plus

import pandas as pd
from sqlalchemy import create_engine

username = quote_plus("root")
password = quote_plus("1qaz@WSX")
server = "127.0.0.1:3307"
db_name = "TESTDB"

conn = create_engine(
    f"mysql+pymysql://{username}:{password}@{server}/{db_name}",
).connect()

In [3]:
print(password)

1qaz%40WSX

In [ ]:
sql = "select * from Staff"
df = pd.read_sql(
    sql, conn,
)
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  001   Mike    002   45      M   60000 2020-10-13 21:41:49
1  002   Judy    002   30      F   48000 2020-10-13 21:41:49
2  003  Allen    001   22      M   50000 2020-10-13 21:41:49
3  004    Tom    002   47      M   47000 2020-10-13 21:41:49
4  005   Jack    003   36      M   52000 2020-10-13 21:41:49
5  006   Abby    002   24      F   45000 2020-10-13 21:41:49
6  007  Trump    001   80      M   80000 2020-10-13 21:41:49
7  008  Marry    003   29      F   87000 2020-10-13 21:41:49

In [6]:
df = pd.read_sql(
    "Staff", conn,
)
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  001   Mike    002   45      M   60000 2020-10-13 21:41:49
1  002   Judy    002   30      F   48000 2020-10-13 21:41:49
2  003  Allen    001   22      M   50000 2020-10-13 21:41:49
3  004    Tom    002   47      M   47000 2020-10-13 21:41:49
4  005   Jack    003   36      M   52000 2020-10-13 21:41:49
5  006   Abby    002   24      F   45000 2020-10-13 21:41:49
6  007  Trump    001   80      M   80000 2020-10-13 21:41:49
7  008  Marry    003   29      F   87000 2020-10-13 21:41:49

In [7]:
df["ID"] = df["ID"].str.replace("00", "01")
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  011   Mike    002   45      M   60000 2020-10-13 21:41:49
1  012   Judy    002   30      F   48000 2020-10-13 21:41:49
2  013  Allen    001   22      M   50000 2020-10-13 21:41:49
3  014    Tom    002   47      M   47000 2020-10-13 21:41:49
4  015   Jack    003   36      M   52000 2020-10-13 21:41:49
5  016   Abby    002   24      F   45000 2020-10-13 21:41:49
6  017  Trump    001   80      M   80000 2020-10-13 21:41:49
7  018  Marry    003   29      F   87000 2020-10-13 21:41:49

In [ ]:
df.to_sql(
    "Staff",
    conn,
    index=False,
    if_exists="append", # insert into
)

8

In [9]:
conn.commit()

In [10]:
df.to_sql(
    "Staff",
    conn,
    index=False,
    if_exists="replace",
)

8

In [11]:
# 連接資料庫
import pymysql

host = 'localhost'
port = 3307  # if you are using docker, you must use 3307, or reserve 3306
user = 'root'
passwd = '1qaz@WSX'
db = 'TESTDB'
charset = 'utf8mb4'

conn = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db, charset=charset)
print('Successfully connected!')

cursor = conn.cursor()

sql = "select * from Staff"
cursor.execute(sql)
data = cursor.fetchall()
data

Successfully connected!

(('011',
  'Mike',
  '002',
  45,
  'M',
  60000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('012',
  'Judy',
  '002',
  30,
  'F',
  48000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('013',
  'Allen',
  '001',
  22,
  'M',
  50000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('014',
  'Tom',
  '002',
  47,
  'M',
  47000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('015',
  'Jack',
  '003',
  36,
  'M',
  52000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('016',
  'Abby',
  '002',
  24,
  'F',
  45000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('017',
  'Trump',
  '001',
  80,
  'M',
  80000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)),
 ('018',
  'Marry',
  '003',
  29,
  'F',
  87000,
  datetime.datetime(2020, 10, 13, 21, 41, 49)))

In [13]:
df = pd.DataFrame(
    data=data,
)
df

     0      1    2   3  4      5                   6
0  011   Mike  002  45  M  60000 2020-10-13 21:41:49
1  012   Judy  002  30  F  48000 2020-10-13 21:41:49
2  013  Allen  001  22  M  50000 2020-10-13 21:41:49
3  014    Tom  002  47  M  47000 2020-10-13 21:41:49
4  015   Jack  003  36  M  52000 2020-10-13 21:41:49
5  016   Abby  002  24  F  45000 2020-10-13 21:41:49
6  017  Trump  001  80  M  80000 2020-10-13 21:41:49
7  018  Marry  003  29  F  87000 2020-10-13 21:41:49

In [14]:
conn.close()

## Auto commit

In [17]:
from urllib.parse import quote_plus

import pandas as pd
from sqlalchemy import create_engine

username = quote_plus("root")
password = quote_plus("1qaz@WSX")
server = "127.0.0.1:3307"
db_name = "TESTDB"

with create_engine(
    f"mysql+pymysql://{username}:{password}@{server}/{db_name}?autocommit=true",
).connect() as conn:
    # Do something to transform dataframe
    df = pd.read_sql("Staff", conn)
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  011   Mike    002   45      M   60000 2020-10-13 21:41:49
1  012   Judy    002   30      F   48000 2020-10-13 21:41:49
2  013  Allen    001   22      M   50000 2020-10-13 21:41:49
3  014    Tom    002   47      M   47000 2020-10-13 21:41:49
4  015   Jack    003   36      M   52000 2020-10-13 21:41:49
5  016   Abby    002   24      F   45000 2020-10-13 21:41:49
6  017  Trump    001   80      M   80000 2020-10-13 21:41:49
7  018  Marry    003   29      F   87000 2020-10-13 21:41:49

In [19]:
df["ID"] = df["ID"].str.replace("01", "02")
df

    ID   Name DeptId  Age Gender  Salary            recordDt
0  021   Mike    002   45      M   60000 2020-10-13 21:41:49
1  022   Judy    002   30      F   48000 2020-10-13 21:41:49
2  023  Allen    001   22      M   50000 2020-10-13 21:41:49
3  024    Tom    002   47      M   47000 2020-10-13 21:41:49
4  025   Jack    003   36      M   52000 2020-10-13 21:41:49
5  026   Abby    002   24      F   45000 2020-10-13 21:41:49
6  027  Trump    001   80      M   80000 2020-10-13 21:41:49
7  028  Marry    003   29      F   87000 2020-10-13 21:41:49

In [20]:
df.columns

Index(['ID', 'Name', 'DeptId', 'Age', 'Gender', 'Salary', 'recordDt'], dtype='str')

In [21]:
df[
    [
        'ID',
        'DeptId',
        'Gender',
        'recordDt',
        'Name',
        'Age',
        'Salary'
    ]
]

    ID DeptId Gender            recordDt   Name  Age  Salary
0  021    002      M 2020-10-13 21:41:49   Mike   45   60000
1  022    002      F 2020-10-13 21:41:49   Judy   30   48000
2  023    001      M 2020-10-13 21:41:49  Allen   22   50000
3  024    002      M 2020-10-13 21:41:49    Tom   47   47000
4  025    003      M 2020-10-13 21:41:49   Jack   36   52000
5  026    002      F 2020-10-13 21:41:49   Abby   24   45000
6  027    001      M 2020-10-13 21:41:49  Trump   80   80000
7  028    003      F 2020-10-13 21:41:49  Marry   29   87000

In [23]:
with create_engine(
    f"mysql+pymysql://{username}:{password}@{server}/{db_name}?autocommit=true",
).connect() as conn:
    # Do something to transform dataframe
    df[
        [
            'ID',
            'DeptId',
            'Gender',
            'recordDt',
            'Name',
            'Age',
            'Salary'
        ]
    ].to_sql(
        "Staff",
        conn,
        if_exists="append",
        index=False,
    )